---
development:
  cloud_name: showcase-technologies
  api_key: '255311393262156'
  api_secret: f8MkspREJDZqfv4JsKwQtpQ7I8Q
  enhance_image_tag: true
  static_image_support: false
  CLOUDINARY_URL=cloudinary://255311393262156:f8MkspREJDZqfv4JsKwQtpQ7I8Q@showcase-technologies
production:
  cloud_name: showcase-technologies
  api_key: '255311393262156'
  api_secret: f8MkspREJDZqfv4JsKwQtpQ7I8Q
  enhance_image_tag: true
  static_image_support: true
  CLOUDINARY_URL=cloudinary://255311393262156:f8MkspREJDZqfv4JsKwQtpQ7I8Q@showcase-technologies
test:
  cloud_name: showcase-technologies
  api_key: '255311393262156'
  api_secret: f8MkspREJDZqfv4JsKwQtpQ7I8Q
  enhance_image_tag: true
  static_image_support: false
  CLOUDINARY_URL=cloudinary://255311393262156:f8MkspREJDZqfv4JsKwQtpQ7I8Q@showcase-technologies
